# Generated by Django 5.1.4 on 2025-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='C:\\Users\\zizo\\Desktop\\programing\\Django\\book_market\\book_market\\media\\users\\2025\\01\\27\\nothing.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
