# Generated by Django 5.1.4 on 2025-02-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_birth_data_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birth_data',
        ),
    ]
